# This is a basic workflow to Test HiCUP

name: HiCUP+_Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, devel, actions ]
  pull_request:
    branches: [ master, devel, actions ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Update Ubuntu
      run: |
        sudo apt-get update 

    - name: Install dependencies
      run: |
        sudo apt install samtools
        sudo apt install bowtie2
        sudo apt install r-base-core
                         
    - name: Download Test Dataset and genome index files and FASTA files
      run: |
        wget -nv https://www.bioinformatics.babraham.ac.uk/projects/hicup/test_dataset.tar.gz
        tar xvzf test_dataset.tar.gz
        mkdir -p Homo_sapiens.GRCh38_Bowtie2_Index_HiCUP
        cd Homo_sapiens.GRCh38_Bowtie2_Index_HiCUP
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes/Human/Homo_sapiens.GRCh38.1.bt2
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes/Human/Homo_sapiens.GRCh38.2.bt2
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes/Human/Homo_sapiens.GRCh38.3.bt2
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes/Human/Homo_sapiens.GRCh38.4.bt2
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes/Human/Homo_sapiens.GRCh38.rev.1.bt2
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes/Human/Homo_sapiens.GRCh38.rev.2.bt2
        cd ..
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.1.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.2.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.3.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.4.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.5.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.6.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.7.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.8.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.9.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.10.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.11.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.12.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.13.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.14.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.15.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.16.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.17.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.18.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.19.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.20.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.21.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.22.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.MT.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.X.fa.gz
        wget -nv http://ftp1.babraham.ac.uk/ftpusr46/FastQ_Screen_Genomes_Bisulfite/Human/GRCh38/Homo_sapiens.GRCh38.dna.chromosome.Y.fa.gz
        
    - name: Run HiCUP
      run: |
        $GITHUB_WORKSPACE/hicup --help
        $GITHUB_WORKSPACE/hicup --version
        $GITHUB_WORKSPACE/hicup_digester --re1 A^AGCTT,HindIII --genome Human38 --zip *.fa.gz
        $GITHUB_WORKSPACE/hicup --digest Digest* --zip --threads 2 --index ./Homo_sapiens.GRCh38_Bowtie2_Index_HiCUP/Homo_sapiens.GRCh38 --shortest 50 --longest 700 test_dataset/*.fastq
        
    - name: Check results
      run: |
         $GITHUB_WORKSPACE/Testing/hicup_checker --threshold 5 --expected test_dataset/HiCUP_summary_test_dataset_results.txt --new HiCUP_summary_report_* 
